package com.zerobase.zerobaseheritage.datatype.exception;

public enum ErrorCode {
  EXTERNALAPI_NOT_FOUND, NULL_POINT_EXCEPTION, HERITAGE_GRADE_NOT_FOUND, LOCATION_OUT_OF_BOUND, NO_HERITAGE_NEARBY, USERID_NON_EXISTENT, HERITAGEID_NON_EXISTENT, HERITAGE_ALREADY_VISITED, UNEXPECTED_REQUEST_FROM_FRONT, THREAD_EXCEPTION,


}
