spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zerobase_heritage?useSSL=false&useServerPrepStmts=false
    username: testuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
