spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zerobase_heritage?useSSL=false&useServerPrepStmts=false
    username: testuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none


    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    rest:
      default-media-type: application/json
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql




